play {
  application.loader = AppLoader

  # HTTP configuration
  server.http.port = 9000

  # Allow large requests (imports)
  http.parser.maxMemoryBuffer = 10m

  # Filters
  filters {
    enabled = []
    enabled += "play.filters.headers.SecurityHeadersFilter"
  }

  # Assets
  assets {
    path = "/public"
    urlPrefix = "/"
  }
}
