name: Build

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: false
      runner-arm64:
        required: false
        type: string
        default: ubuntu-24.04-arm
      runner-amd64:
        required: false
        type: string
        default: ubuntu-latest

env:
  NODE_VERSION: 20
  JAVA_VERSION: 17
  DOCKER_IMAGE: elkozmon/zoonavigator
  DOCS_URL: https://zoonavigator.elkozmon.com

permissions:
  contents: read

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.set-vars.outputs.app-version }}
      snap-channel: ${{ steps.set-vars.outputs.snap-channel }}
      docs-url: ${{ steps.set-vars.outputs.docs-url }}
    steps:
      - name: Set variables
        id: set-vars
        run: |
          ref="${GITHUB_REF_NAME#v}"

          # is this a semver release?
          if [[ "${ref}" =~ ^[0-9]+(\.[0-9]+){2,3}$ ]];
          then
              app_version="${ref}"
              snap_channel="stable"
              docs_url="${{ env.DOCS_URL }}/en/${ref}"
          else
              app_version="latest-${GITHUB_SHA::12}"
              snap_channel="beta"
              docs_url="${{ env.DOCS_URL }}/en/latest"
          fi

          echo "app-version=${app_version}" >> "$GITHUB_OUTPUT"
          echo "snap-channel=${snap_channel}" >> "$GITHUB_OUTPUT"
          echo "docs-url=${docs_url}" >> "$GITHUB_OUTPUT"

  build-docker:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    runs-on: ${{ matrix.architecture == 'arm64' && inputs.runner-arm64 || inputs.runner-amd64 }}
    needs:
      - setup-env
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
          labels: |
            org.opencontainers.image.documentation=${{ needs.setup-env.outputs.docs-url }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.workspace }}/build/docker/Dockerfile
          platforms: linux/${{ matrix.architecture }}
          push: false
          outputs: |
            type=image,"name=${{ env.DOCKER_IMAGE }}",push-by-digest=true,push=true
            type=local,dest=out
          build-args: |
            APP_VERSION=${{ needs.setup-env.outputs.app-version }}
            DOCS_URL=${{ needs.setup-env.outputs.docs-url }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=buildkit-${{ matrix.architecture }}
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.architecture }}

      - name: Package jars
        if: matrix.architecture == 'amd64'
        run: |
          mkdir -p ${{ runner.temp }}/jars
          tar -cvzf ${{ runner.temp }}/jars/jars.tar.gz -C out/app lib

      - name: Upload jars
        if: matrix.architecture == 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: ${{ runner.temp }}/jars/jars.tar.gz
          if-no-files-found: error

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.architecture }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error

  build-snap:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    runs-on: ${{ matrix.architecture == 'arm64' && inputs.runner-arm64 || inputs.runner-amd64 }}
    needs:
      - setup-env
      - build-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download jars
        id: download-jars
        uses: actions/download-artifact@v4
        with:
          name: jars

      - name: Prepare Snap files
        run: |
          echo "${{ needs.setup-env.outputs.app-version }}" \
            > ${GITHUB_WORKSPACE}/build/snap/local/version

          tar \
            -xvf ${{ steps.download-jars.outputs.download-path }}/jars.tar.gz \
            -C ${GITHUB_WORKSPACE}/build/snap/local

      - name: Build Snap
        id: build-snap
        uses: snapcore/action-build@v1
        with:
          path: build/

      - name: Upload Snap
        uses: actions/upload-artifact@v4
        with:
          name: snap-${{ matrix.architecture }}
          path: ${{ steps.build-snap.outputs.snap }}

  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - docker
          - snap
        zookeeper:
          - 3.9
        architecture:
          - amd64
          - arm64
    runs-on: ${{ matrix.architecture == 'arm64' && inputs.runner-arm64 || inputs.runner-amd64 }}
    env:
      ZK_PORT: 2181
      ZN_PORT: 9000
    needs:
      - setup-env
      - build-docker
      - build-snap
    services:
      zookeeper:
        image: zookeeper:${{ matrix.zookeeper }}
        ports:
          - 2181:2181
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: e2e/package-lock.json

      - name: Install e2e dependencies
        working-directory: e2e
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps --only-shell

      # Docker-specific steps
      - name: Download digest
        if: matrix.platform == 'docker'
        id: download-digest
        uses: actions/download-artifact@v4
        with:
          name: digests-${{ matrix.architecture }}

      - name: Start ZooNavigator Docker container
        if: matrix.platform == 'docker'
        working-directory: ${{ steps.download-digest.outputs.download-path }}
        run: |
          docker run -d \
            --name zoonavigator-test \
            --network host \
            -e HTTP_PORT=${{ env.ZN_PORT }} \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s' "$(ls | head -n1)")

      # Snap-specific steps
      - name: Download Snap
        if: matrix.platform == 'snap'
        id: download-snap
        uses: actions/download-artifact@v4
        with:
          name: snap-${{ matrix.architecture }}

      - name: Install Snap daemon
        if: matrix.platform == 'snap'
        run: |
          sudo apt update
          sudo apt install -y snapd

      - name: Install ZooNavigator Snap
        if: matrix.platform == 'snap'
        run: |
          sudo snap install --dangerous ${{ steps.download-snap.outputs.download-path }}/zoonavigator_${{ needs.setup-env.outputs.app-version }}_${{ matrix.architecture }}.snap

      - name: Configure ZooNavigator Snap
        if: matrix.platform == 'snap'
        run: |
          sudo snap set zoonavigator zoonavigator.server.http.port=${{ env.ZN_PORT }}

      - name: Start ZooNavigator Snap
        if: matrix.platform == 'snap'
        run: |
          sudo snap start zoonavigator

      # Common steps
      - name: Wait for ZooNavigator to startup
        uses: emilioschepis/wait-for-endpoint@v1.0.4
        with:
          url: http://localhost:${{ env.ZN_PORT }}
          method: GET
          expected-status: 200
          timeout: 60000
          interval: 1000

      - name: Run e2e tests
        working-directory: e2e
        env:
          CI: true
          ZK_TEST_NODE: /test-${{ matrix.platform }}-${{ github.run_id }}
          ZK_CONNECTION_STRING: localhost:${{ env.ZK_PORT }}
          ZN_BASE_URL: http://localhost:${{ env.ZN_PORT }}
        run: npm test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.platform }}-${{ matrix.architecture }}
          path: e2e/playwright-report/
          retention-days: 7

  publish-docker:
    runs-on: ubuntu-latest
    if: inputs.publish
    needs:
      - setup-env
      - build-docker
      - test-e2e
    steps:
      - name: Download digests
        id: download-digests
        uses: actions/download-artifact@v4
        with:
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=auto
          tags: |
            type=pep440,pattern={{version}}
            type=raw,value=unstable

      - name: Create manifest list and push
        working-directory: ${{ steps.download-digests.outputs.download-path }}
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s ' *)

  publish-snap:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    if: inputs.publish
    needs:
      - setup-env
      - build-snap
      - test-e2e
    steps:
      - name: Download Snap
        id: download-snap
        uses: actions/download-artifact@v4
        with:
          name: snap-${{ matrix.architecture }}

      - name: Publish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_CREDENTIALS }}
        with:
          snap: ${{ steps.download-snap.outputs.download-path }}/zoonavigator_${{ needs.setup-env.outputs.app-version }}_${{ matrix.architecture }}.snap
          release: ${{ needs.setup-env.outputs.snap-channel }}

  cleanup:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build-docker
      - build-snap
      - test-e2e
      - publish-docker
      - publish-snap
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            jars
            snap-amd64
            snap-arm64
            digests-amd64
            digests-arm64
