name: Publish

on:
  push:
    branches: [ master, main ]
    tags: [ '*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      skip-build: true

  publish:
    uses: ./.github/workflows/build.yml
    needs:
      - test
    with:
      publish: true
